### ISSUE TITLE
Image ID is not being updated.

### ISSUE THREAD

**Issue by ghost** [michalsternadel/mgs_zbxicons#2]
After running the script it does not update the Database ids imageid.
this makes it that u cant add new images on the zabbix server.

These 2 commands should fix this problems
SELECT max(imageid)images FROM zabbix.images;  
UPDATE `zabbix`.`ids` SET `nextid` = '_________' WHERE (`table_name` = 'images') and (`field_name` = 'imageid'); 

First command is to se what the max image id is
second one is to update the image id
_________ = should the the max image id

I ad a ticket open on the support.zabbix because we had a db error:
https://support.zabbix.com/browse/ZBX-16758

**Comment by michalsternadel** [comment]
Fixed. Thanks.
