### ISSUE TITLE
Error in script on MariaDB

### ISSUE THREAD

**Issue by sabino08** [michalsternadel/mgs_zbxicons#4]
In MariaDB the sql files send this error:
ERROR 1064 (42000) at line 2: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'x'9504e470da1a0a0000000d4948445200000080000000800806000000c33e61cb0000216449...' at line 1

**Comment by michalsternadel** [comment]
Hello,
I can't reproduce this error, tested on 10.3.20-MariaDB with fresh zabbix install with no problems whatsoever.
My steps was:
```
python3  ./mgs_zbxicons.py
mysql -u root -p zabbix < ./sql/upgrade.sql

```
Please provide what version of db engine are you using and your steps, perhaps I'm missing something.

**Comment by michalsternadel** [comment]
Reopen, if problem still persist. Have a nice day!
