### ISSUE TITLE
postgresql no work

### ISSUE THREAD

**Issue by red-november-ce** [michalsternadel/mgs_zbxicons#5]
cannot be imported into the database postgresql

**Comment by michalsternadel** [comment]
I've never used postgresql as a backend for Zabbix installation. Clone commit aae93c3559c6a27ae038236af0bf06fbf87173dd, do backup of your database and check with mgs_zbxicons-psql.sql file.
I've tested the installation and update procedure on a fresh docker zabbix-psql instance and it worked flawlessly.
Have a nice day.

**Comment by red-november-ce** [comment]
thanks:)
