### ISSUE TITLE
My Zabbix Server under ubuntu can't edit map

### ISSUE THREAD

**Issue by chuyuk** [michalsternadel/mgs_zbxicons#7]
After installing the Map, I can view the existing map, but the edit will only show a blank page...
![image](https://user-images.githubusercontent.com/98506547/151291009-bbefa64e-d3df-4f06-ab3b-73c7fa04f321.png)

Wehn I try Edit some map
![image](https://user-images.githubusercontent.com/98506547/151291094-6c52935d-b933-4ef6-9546-17a7ebf41d58.png)
![image](https://user-images.githubusercontent.com/98506547/151291112-12844f70-ead5-4772-8aec-14c17c31a45a.png)

So How I can solve it?

The current Zabbix Package Version is 5.4 / Ubuntu / 20.04 (Focal) / MySQL Db and Apache Server, Do I need to change to use NGINX?

**Comment by chuyuk** [comment]
https://github.com/michalsternadel/mgs_zbxicons/issues/6

Following the post I tried to modify memory_limit from 128M to 256M or 1024M is the same result.  >_<
![image_712](https://user-images.githubusercontent.com/98506547/151294872-fd870f0c-1cbc-4230-a4d8-5d002ab261d0.jpg)

**Comment by chuyuk** [comment]
I am stupid, the problem solved!!!

I should modify /etc/zabbix/apache.conf instead /etc/php/7.4/apache2/php.ini

**Comment by chuyuk** [comment]
Any quick method to remove imported icons?

**Comment by michalsternadel** [comment]
Hello,
the dirtiest way I could imagine is:
`grep -v "update ids set" ./sql/mgs_zbxicons-mysql.sql |awk {'print "delete from images where name=" $11'} | sed 's/,/;/g'`
Please make a backup copy of the database before this operation.

**Comment by didli** [comment]
Hi ! First, thank you for the icons set ^^. ~~Same issue here : trying to edit a map will either give a blank page or a blank map. 
Hitting F5 a few times to refresh can help to get editing back, but a bit unstable. Any other tweaks besides the php memory limit maybe ?
I'm running a standard zabbix install (mysql/apache) inside a not-so-standard LXC container (centos stream 8).~~ 
EDIT : nevermind, got it to work (for now ?). For some reason, the memory limit wasn't applied, even after multiple php/apache restart.

**Comment by AskerMasker** [comment]
Same problem, looks like only in Brave browser. Firefox working well.
Zabbix 6.2.6
```
cat /etc/zabbix/php-fpm.conf

...
php_value[max_execution_time] = 600
php_value[memory_limit] = 512M
php_value[post_max_size] = 16M
php_value[upload_max_filesize] = 2M
php_value[max_input_time] = 600
php_value[max_input_vars] = 10000
```

Icons and labels don't visible in edit mode. It doesn't matter if I use zabbix or tango icons. I can find them only blindly and click.

![image](https://user-images.githubusercontent.com/125661818/219651293-6efbd783-fec4-4814-951d-33acedf9db07.png)

Nginx error.log is empty. As you see I already added php memory_limit and max_execution_time.
Also can't find any related problems in browser console...

**Comment by michalsternadel** [comment]
@AskerMasker I can confirm that problem exists in Brave browser. Try opening in incognito mode - works for me:
![image](https://user-images.githubusercontent.com/38687075/219754824-ff6c122e-a765-4c06-8ad6-e9a2d4b11261.png)

Have a nice day!

**Comment by AskerMasker** [comment]
Also Dashboard widget in Brave show nothing. Clearing cookie/cache solving problem for a while.

![image](https://user-images.githubusercontent.com/125661818/220043786-8ab20c8a-2ff7-43f9-a814-7d60e741ab69.png)
